site_name: John Nguyen
site_description: Personal Website by John Nguyen
site_url: https://nguy4130.github.io/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
repo_url: "https://github.com/nguy4130/nguy4130.github.io"
repo_name: "GitHub"
