site_name: John Nguyen
site_description: Personal Website by John Nguyen
site_url: https://nguy4130.github.io/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
repo_url: "https://github.com/nguy4130/nguy4130.github.io"
repo_name: "GitHub"
extra: 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nguy4130
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lamnguyen1105/
    - icon: fontawesome/solid/paper-plane
      link: mailto:<lamnguyen110500@gmail.com>